name: Validate Helm Chart

on:
  push:
    branches: [main]
    paths:
      - 'templates/Chart.yaml'
      - 'templates/values.yaml'
      - 'templates/**'
      - '.github/workflows/helm-push.yaml'
permissions:
  contents: read

jobs:
  validate-helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Lint Helm chart
        run: |
          helm lint .