name: Build and Push Helm Chart to GHCR

on:
  push:
    branches: [main]
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - '.github/workflows/helm-push.yaml'

jobs:
  push-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Log in to GitHub Container Registry (GHCR)
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Package Helm chart
        run: |
          mkdir -p packaged
          helm dependency update .
          helm package . --destination packaged

      - name: Push Helm chart to GHCR
        run: |
          helm push packaged/*.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
